name: Myfirst Workflow
on: push
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World Step
              run: echo Hello, world!
    job-2:
        runs-on: ubuntu-latest
        steps:
            - name: Second And Final Step
              run: echo Hello, world!          